/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://24rnkeeov5gzxiwmipst2plzwi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ihmfbkdvtvbv7ivtjj5nxsg4sm",
    "aws_cognito_identity_pool_id": "us-west-2:55b12a93-a0b0-4df9-a1f9-38d455a2e144",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_m8DR9tlBZ",
    "aws_user_pools_web_client_id": "1ojm6ripf5un9qrcajnvd9r4h6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
